project 'BetterClassEval.xcodeproj'

platform :ios, '12.1'

target 'BetterClassEval' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BetterClassEval
  pod 'SwiftSoup'
  pod 'Alamofire', '~> 4.7'
  pod 'SwiftyJSON'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  target 'BetterClassEvalTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BetterClassEvalUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
