# Uncomment the next line to define a global platform for your project
platform :ios, '12.1'

target 'BetterClassEval' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftSoup'

  # Pods for BetterClassEval

  target 'BetterClassEvalTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BetterClassEvalUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
