project 'BetterClassEval.xcodeproj'

platform :ios, '12.1'

target 'BetterClassEval' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BetterClassEval
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'InstantSearchClient'

  target 'BetterClassEvalTests' do
    inherit! :search_paths
  end

  target 'BetterClassEvalUITests' do
    inherit! :search_paths
  end

end
